"""Updates column name to task_ids

Revision ID: 86a571b35385
Revises: f01eb1267087
Create Date: 2021-10-29 10:20:03.517613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86a571b35385'
down_revision = 'f01eb1267087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_ids', sa.JSON(), nullable=True))
    op.drop_column('goal', 'tasks_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('tasks_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('goal', 'task_ids')
    # ### end Alembic commands ###
