"""Updates column name to tasks

Revision ID: 89a471cff06b
Revises: 86a571b35385
Create Date: 2021-10-29 10:21:20.147550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89a471cff06b'
down_revision = '86a571b35385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('tasks', sa.JSON(), nullable=True))
    op.drop_column('goal', 'task_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('goal', 'tasks')
    # ### end Alembic commands ###
