"""Add tasks_id column to Goal

Revision ID: f01eb1267087
Revises: 70e2fca78371
Create Date: 2021-10-29 10:16:00.253669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01eb1267087'
down_revision = '70e2fca78371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('tasks_ids', sa.JSON(), nullable=True))
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    op.drop_column('goal', 'tasks_ids')
    # ### end Alembic commands ###
